apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-servicemonitor
  namespace: monitoring
  labels:
    release: kps          
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app: flask-app      
  endpoints:
    - port: http          
      path: /metrics
      interval: 15s
